# Store data in a matrix and write in a .csv file 
-> 10% testdata and 90% traindata

In [90]:
import numpy as np

In [91]:
a = np.zeros((1,9))

In [92]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [93]:
for i in range(1,30):
    a = np.insert(a, a.shape[0], [i,i,i,i,i,i,i,i,i], 0)

In [94]:
a

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [11., 11., 11., 11., 11., 11., 11., 11., 11.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [15., 15., 15., 15., 15., 15., 15., 15., 15.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16.],
       [17., 17., 17., 17., 17., 17., 17., 17., 17.],
       [18., 18., 18., 18., 

In [96]:
a.shape

(30, 9)

In [115]:
testCount = round(a.shape[0]/10)

In [116]:
testCount

3

In [117]:
testArray = a[np.arange(testCount,a.shape[0],testCount),:]
trainArray = a
trainArray = np.delete(trainArray, np.arange(testCount,a.shape[0],testCount), 0)

In [118]:
testArray

array([[ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [15., 15., 15., 15., 15., 15., 15., 15., 15.],
       [18., 18., 18., 18., 18., 18., 18., 18., 18.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [24., 24., 24., 24., 24., 24., 24., 24., 24.],
       [27., 27., 27., 27., 27., 27., 27., 27., 27.]])

In [119]:
trainArray

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [11., 11., 11., 11., 11., 11., 11., 11., 11.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16.],
       [17., 17., 17., 17., 17., 17., 17., 17., 17.],
       [19., 19., 19., 19., 19., 19., 19., 19., 19.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [22., 22., 22., 22., 22., 22., 22., 22., 22.],
       [23., 23., 23., 23., 23., 23., 23., 23., 23.],
       [25., 25., 25., 25., 25., 25., 25., 25., 25.],
       [26., 26., 26., 26., 

In [121]:
np.savetxt("..\data\ExportedDatabase.csv", a, delimiter=";")

In [125]:
np.savetxt("..\data\ExportedDatabaseTrain.csv", trainArray, delimiter=";", fmt='%4d')

In [123]:
np.savetxt("..\data\ExportedDatabaseTest.csv", testArray, delimiter=";", fmt='%4d')